#pragma once

// City Life Core recommended SDK umbrella header.
//
// This header intentionally includes the stable-candidate runtime/economy/data
// surface for external SDK users. It does not include raw persistence internals,
// demo-only helpers, or experimental order/data-pack APIs by default.

#include "clc/core/EventLog.hpp"
#include "clc/core/Ids.hpp"
#include "clc/core/Result.hpp"
#include "clc/core/Time.hpp"
#include "clc/core/Version.hpp"

#include "clc/data/DataRegistry.hpp"
#include "clc/data/Definitions.hpp"
#include "clc/data/Validation.hpp"

#include "clc/economy/Ledger.hpp"
#include "clc/economy/Market.hpp"
#include "clc/economy/Trade.hpp"

#include "clc/sim/ActionBridge.hpp"
#include "clc/sim/ActionAuthority.hpp"
#include "clc/sim/Caravans.hpp"
#include "clc/sim/ContractRewards.hpp"
#include "clc/sim/Contracts.hpp"
#include "clc/sim/CoreCompletionReadiness.hpp"
#include "clc/sim/CoreSystemsAudit.hpp"
#include "clc/sim/DeepReplayCoverage.hpp"
#include "clc/sim/DeepSystemsDiagnostics.hpp"
#include "clc/sim/DeepSimulationSystems.hpp"
#include "clc/sim/EconomyDepth.hpp"
#include "clc/sim/Factions.hpp"
#include "clc/sim/GameDeveloperHandoffCatalog.hpp"
#include "clc/sim/GameDeveloperHandoff.hpp"
#include "clc/sim/GameProfileAdoption.hpp"
#include "clc/sim/GameProfileChecklist.hpp"
#include "clc/sim/GameProfileScenarios.hpp"
#include "clc/sim/GameProfileValidation.hpp"
#include "clc/sim/GameProfileValidationMarkdown.hpp"
#include "clc/sim/GameProfiles.hpp"
#include "clc/sim/Logistics.hpp"
#include "clc/sim/LargeWorld.hpp"
#include "clc/sim/MultiplayerEconomySafety.hpp"
#include "clc/sim/MultiplayerLoadDiagnostics.hpp"
#include "clc/sim/MultiplayerReplay.hpp"
#include "clc/sim/Ownership.hpp"
#include "clc/sim/PlatformCore.hpp"
#include "clc/sim/PlatformReadiness.hpp"
#include "clc/sim/Pre3Readiness.hpp"
#include "clc/sim/Production.hpp"
#include "clc/sim/RegionalSimulationSystems.hpp"
#include "clc/sim/RuntimeProcessorOrchestration.hpp"
#include "clc/sim/Routes.hpp"
#include "clc/sim/RuntimeCoreSystems.hpp"
#include "clc/sim/SaveReplayFixtures.hpp"
#include "clc/sim/ScaleDiagnostics.hpp"
#include "clc/sim/ServerAuthoritative.hpp"
#include "clc/sim/SettlementDevelopment.hpp"
#include "clc/sim/Settlement.hpp"
#include "clc/sim/SdkHandoffManifest.hpp"
#include "clc/sim/SnapshotSync.hpp"
#include "clc/sim/SimulationEngine.hpp"
#include "clc/sim/SimulationProcessor.hpp"
#include "clc/sim/SimulationPersistenceReplay.hpp"
#include "clc/sim/SimulationRuntime.hpp"
#include "clc/sim/SimulationRuntimeEvents.hpp"
#include "clc/sim/SimulationRuntimePersistenceValidation.hpp"
#include "clc/sim/SimulationRuntimeScenario.hpp"
#include "clc/sim/SimulationRuntimeTick.hpp"
#include "clc/sim/SimulationRuntimeWorkflow.hpp"
#include "clc/sim/Storage.hpp"
